# Generated by Django 2.0.6 on 2018-07-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=120)),
                ('target', models.CharField(max_length=20)),
                ('icono', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.List')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOptionStatusNotAllowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=90)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_not_alloweds', to='dashboard.MenuOption')),
            ],
        ),
    ]
