# Generated by Django 2.0.6 on 2018-08-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='css_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
