# Generated by Django 2.0.6 on 2018-07-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20180212_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationpending',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivationPending',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
