# Generated by Django 2.0.6 on 2018-07-09 19:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('about', models.TextField()),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('place', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('max_quote_participants', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('answer', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ParticipantStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('birthdate', models.CharField(blank=True, max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(null=True, upload_to='persons')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_assistance_confirmated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('about_us', models.TextField()),
                ('title_aplication_session', models.CharField(max_length=64)),
                ('text_aplication_session', models.TextField()),
                ('subtext_aplication_session', models.TextField(blank=True, null=True)),
                ('title_coach_session', models.CharField(max_length=64)),
                ('subtitle_coach_session', models.CharField(max_length=120)),
                ('text_coach_session', models.TextField()),
                ('title_organizer_session', models.CharField(max_length=64)),
                ('subtitle_organizer_session', models.CharField(blank=True, max_length=120, null=True)),
                ('title_sponsor_session', models.CharField(max_length=64)),
                ('subtitle_sponsor_session', models.CharField(blank=True, max_length=120, null=True)),
                ('participant_sucess', models.TextField()),
                ('participant_warning', models.TextField()),
                ('coach_success', models.TextField()),
                ('btn_inscription', models.CharField(max_length=30)),
                ('text_form_inscription_participant', models.TextField(blank=True, null=True)),
                ('text_form_inscription_sponsor', models.TextField(blank=True, null=True)),
                ('text_footer', models.CharField(blank=True, max_length=120, null=True)),
                ('picture_1_application', models.ImageField(blank=True, null=True, upload_to='portal')),
                ('picture_2_application', models.ImageField(blank=True, null=True, upload_to='portal')),
                ('picture_bg_coach', models.ImageField(blank=True, null=True, upload_to='portal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portal')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('btn_text', models.CharField(max_length=64)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Portal')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Person')),
                ('github_user', models.CharField(blank=True, max_length=120, null=True)),
                ('agree_work_with_windows', models.CharField(choices=[('', '-------------'), ('Si', 'Si'), ('No', 'No')], default='KG', max_length=2)),
                ('time_install_before_workshop', models.CharField(choices=[('', '-------------'), ('Si', 'Si'), ('No', 'No')], default='KG', max_length=2)),
                ('time_meet_before_workshop', models.CharField(choices=[('', '-------------'), ('Si', 'Si'), ('No', 'No')], default='KG', max_length=2)),
                ('experience_teaching', models.TextField(blank=True, null=True)),
                ('want_be_add_website', models.CharField(choices=[('', '-------------'), ('Si', 'Si'), ('No', 'No')], default='KG', max_length=2)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('languages_speak', models.ManyToManyField(to='event.Languages')),
                ('operating_systems', models.ManyToManyField(to='event.OperatingSystem')),
            ],
            bases=('event.person',),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Person')),
                ('programing_knowledge', models.TextField(blank=True, null=True)),
                ('current_ocupation', models.TextField()),
                ('reason_assistance', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('operation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.OperatingSystem')),
                ('programing_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ProgramingLevel')),
            ],
            options={
                'ordering': ('-id',),
            },
            bases=('event.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='event.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Portal'),
        ),
    ]
