# Generated by Django 2.0.6 on 2018-07-09 19:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='portal',
        ),
        migrations.AddField(
            model_name='portal',
            name='slider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Slider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
