# Generated by Django 2.0.6 on 2018-07-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180717_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Portal'),
        ),
    ]
