# Generated by Django 2.0.6 on 2018-07-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180718_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='btn_inscription',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='coach_success',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='participant_sucess',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='participant_warning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Slider'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='subtitle_coach_session',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='text_aplication_session',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='text_coach_session',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='title_aplication_session',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='title_coach_session',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='title_organizer_session',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='title_sponsor_session',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
