# Generated by Django 2.0.6 on 2018-07-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180718_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.ParticipantStatus'),
        ),
        migrations.AddField(
            model_name='participantstatus',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
