# Generated by Django 2.0.6 on 2018-07-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20180724_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantstatus',
            name='order',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
