# Generated by Django 2.0.6 on 2018-07-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_participantstatus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='persons'),
        ),
    ]
