# Generated by Django 2.0.6 on 2018-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20180724_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='barcode',
            field=models.FileField(blank=True, null=True, upload_to='barcode'),
        ),
        migrations.AddField(
            model_name='participant',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
