# Generated by Django 2.0.6 on 2018-07-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20180725_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='barcode_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
